services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3100:3000
    volumes:
      - data:/app/config # Make sure your local config directory exists
      - images:/app/public/images
    restart: unless-stopped
    pull_policy: always
    environment:
      HOMEPAGE_ALLOWED_HOSTS: olympus.ctakos.com

volumes:
  data:
  images:
