services:
  app:
    image: 'jc21/nginx-proxy-manager:2.12.2'
    restart: unless-stopped
    pull_policy: always
    ports: 
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - certs:/etc/letsencrypt
    network_mode: "host"
    command: sleep 60

volumes:
  data:
  certs:
