services:
  # Nginx Proxy Manager
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports: 
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm_data:/data
      - npm_certs:/etc/letsencrypt
  golinks:
    image: trotto/go-links
    container_name: golinks
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      # This allows you to use it without a complicated login setup for home use
      - ALLOW_NO_AUTH=true 
    volumes:
      - golinks_data:/data
    networks:
      - default

volumes:
  npm_data:
  npm_certs:
  golinks_data: