services:
  # Nginx Proxy Manager
  nappm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports: 
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - certs:/etc/letsencrypt
  golinks:
      image: nicholaswilde/golinks:latest
      container_name: golinks
      restart: unless-stopped
      expose:
        - "8000"
      volumes:
        - golinks_data:/app/data
      networks:
        - default

volumes:
  data:
  certs:
  golinks_data: