services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    pull_policy: always
    ports: 
      - '8080:80'
      - '81:81'
      - '8443:443'
    volumes:
      - data:/data
      - certs:/etc/letsencrypt
    command: sleep 60

volumes:
  data:
  certs:
