volumes:
  pihole:
  dnsmasq.d:

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    pull_policy: always
    network_mode: host
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: ${WEBPASSWORD}
      FTLCONF_webserver_port: "8081"
      FTLCONF_webserver_https_port: "0"


    volumes:
      - pihole:/etc/pihole
      - dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
